package com.gestion.commandes.gui;

import com.gestion.commandes.models.Client;
import com.gestion.commandes.database.ClientDAO;

import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;

public class AddClientDialog extends JDialog {
    private JTextField nomField;
    private JTextField emailField;
    private JTextField telephoneField;
    private JButton saveButton;
    private ClientPanel clientPanel;

    public AddClientDialog(JFrame parent, ClientPanel clientPanel) {
        super(parent, "Ajouter un Client", true);
        this.clientPanel = clientPanel;

        setSize(300, 200);
        setLocationRelativeTo(parent);

        // Create form fields
        nomField = new JTextField(20);
        emailField = new JTextField(20);
        telephoneField = new JTextField(20);

        // Create save button
        saveButton = new JButton("Enregistrer");
        saveButton.addActionListener(e -> saveClient());

        // Add components to the dialog
        JPanel panel = new JPanel(new GridLayout(4, 2));
        panel.add(new JLabel("Nom:"));
        panel.add(nomField);
        panel.add(new JLabel("Email:"));
        panel.add(emailField);
        panel.add(new JLabel("Téléphone:"));
        panel.add(telephoneField);
        panel.add(new JLabel()); // Empty label for spacing
        panel.add(saveButton);

        add(panel);
    }

    private void saveClient() {
        String nom = nomField.getText();
        String email = emailField.getText();
        String telephone = telephoneField.getText();

        if (nom.isEmpty() || email.isEmpty() || telephone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Client client = new Client(0, nom, email, telephone); // ID will be auto-generated by the database
        ClientDAO clientDAO = new ClientDAO();

        try {
            clientDAO.addClient(client);
            JOptionPane.showMessageDialog(this, "Client ajouté avec succès!", "Succès", JOptionPane.INFORMATION_MESSAGE);
            clientPanel.loadClients(); // Refresh the client list
            dispose(); // Close the dialog
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout du client.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }
}