package com.gestion.commandes.gui;

import com.gestion.commandes.models.Produit;
import com.gestion.commandes.database.ProduitDAO;

import javax.swing.*;
import java.awt.*;
import java.sql.SQLException;

public class AddProduitDialog extends JDialog {
    private JTextField nomField;
    private JTextField prixField;
    private JTextField quantiteField;
    private JButton saveButton;
    private ProduitPanel produitPanel;

    public AddProduitDialog(JFrame parent, ProduitPanel produitPanel) {
        super(parent, "Ajouter un Produit", true);
        this.produitPanel = produitPanel;

        setSize(300, 200);
        setLocationRelativeTo(parent);

        // Create form fields
        nomField = new JTextField(20);
        prixField = new JTextField(20);
        quantiteField = new JTextField(20);

        // Create save button
        saveButton = new JButton("Enregistrer");
        saveButton.addActionListener(e -> saveProduit());

        // Add components to the dialog
        JPanel panel = new JPanel(new GridLayout(4, 2));
        panel.add(new JLabel("Nom:"));
        panel.add(nomField);
        panel.add(new JLabel("Prix:"));
        panel.add(prixField);
        panel.add(new JLabel("Quantité en Stock:"));
        panel.add(quantiteField);
        panel.add(new JLabel()); // Empty label for spacing
        panel.add(saveButton);

        add(panel);
    }

    private void saveProduit() {
        String nom = nomField.getText();
        double prix;
        int quantite;

        try {
            prix = Double.parseDouble(prixField.getText());
            quantite = Integer.parseInt(quantiteField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Veuillez entrer un prix et une quantité valides.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (nom.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Produit produit = new Produit(0, nom, prix, quantite); // ID will be auto-generated by the database
        ProduitDAO produitDAO = new ProduitDAO();

        try {
            produitDAO.addProduit(produit);
            JOptionPane.showMessageDialog(this, "Produit ajouté avec succès!", "Succès", JOptionPane.INFORMATION_MESSAGE);
            produitPanel.loadProduits(); // Refresh the product list
            dispose(); // Close the dialog
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout du produit.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }
}